#!/usr/bin/env bash

apt update -y
apt install git ansible -y

mkdir ~/git

git clone http://github.com/alefcarlos/wsl2-ubuntu-playbook ~/git/wsl2-ubuntu-playbook/

cd ~/git/wsl2-ubuntu-playbook/

read -p "Type the user name: " user_name

ansible-playbook playbook.yml --extra-vars="user_name=${user_name}" --ask-become-pass
